---
  dataSource: "prs"
  changelogFilename: "CHANGELOG.md"
  onlyMilestones: false
  includeMessages: "all"
  ignoreIssuesWith:
    - "support"
  ignoreLabels:
    - "duplicate"
    - "invalid"
    - "wontfix"
  groupBy:
    New features:
      - "feature"
    Bug Fixes:
      - "bug"
    Enhancements:
      - "enhancement"
    Internationalisation:
      - "i18n"
    Theme Meta:
      - "meta"
    Uncategorised:
      - "closed"
  template:
    group: "\n#### {{heading}}\n"
