---
  dataSource: "prs"
  changelogFilename: "CHANGELOG.md"
  onlyMilestones: false
  includeMessages: "all"
  ignoreIssuesWith:
    - "support"
  ignoreLabels:
    - "duplicate"
    - "invalid"
    - "wontfix"
  groupBy:
    🚀 New features:
      - "feature"
    👾 Fixes:
      - "bug"
      - "fix"
    ☠️ Hotfixes:
      - "hotfix"
    Uncategorized:
      - "closed"
  template:
    group: "\n## {{heading}}\n"
    commit: "-> [{{message}}]({{url}}) - {{author}} : {{name}}"
    release: "##:D {{release}} ({{date}})\n{{body}}"
    releaseSeparator: "\n---\n\n"
    issue: "- [{{text}}]({{url}}) `{{name}}` by [@{{user_login}}]({{user_url}})"
    changelogTitle: "# :Das Changelog\n\n"
